#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               false
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.15
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config window_border_radius         11
yabai -m config window_animation_duration    0.15
yabai -m config active_window_border_color   0xffe1e3e4
yabai -m config normal_window_border_color   0xff2a2f38
yabai -m config insert_feedback_color        0xff9dd274
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config external_bar                 all:39:0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   8

# spaces
yabai -m space 1 --label "Browser"
yabai -m space 2 --label "Terminal"
yabai -m space 3 --label "Notes"
yabai -m space 4 --label "Social"
yabai -m space 5 --label "Productivity"
yabai -m space 6 --label "Music"

# Web browsers
yabai -m rule --add app="^Google Chrome|Arc|Safari$" space=1
# Terminal
yabai -m rule --add app="^(iTerm2|Terminal|Alacritty|kitty)$" space=2
# Notes
yabai -m rule --add app="^(Notion|Obsidian|Notes|Reminders)$" space=3
# Social
yabai -m rule --add app="^(WhatsApp|Messages|Slack)$" space=4
# Productivity
yabai -m rule --add app="^(Mail|Keynote|Numbers|Pages|Calendar)$" space=5
# Music
yabai -m rule --add app="^(Music)$" space=6

# apps to not manage (ignore)
yabai -m rule --add app="^(Finder|System Settings|Archive Utility|Creative Cloud|Logi Options|Raycsat|Bitwarden|CleanMyMac X|Karabiner-Elements|Karabiner-EventViewer|Setapp|Stats|ClearVPN|DBngin|FaceTime)$" manage=off

echo "yabai configuration loaded.."
