#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Setting up the general bar appearance and default values
sketchybar --bar height=39
sketchybar --bar color=$BAR_COLOR
sketchybar --bar shadow=on
sketchybar --bar position=top
sketchybar --bar sticky=on
sketchybar --bar padding_right=7
sketchybar --bar padding_left=7
sketchybar --bar corner_radius=9
sketchybar --bar y_offset=10
sketchybar --bar margin=10
sketchybar --bar blur_radius=20
sketchybar --bar notch_width=0

sketchybar --default updates=when_shown
sketchybar --default icon.font="$FONT:Semibold:13.0"
sketchybar --default icon.color=$ICON_COLOR
sketchybar --default icon.padding_left=$PADDINGS
sketchybar --default icon.padding_right=$PADDINGS
sketchybar --default label.font="$FONT:Semibold:13.0"
sketchybar --default label.color=$LABEL_COLOR
sketchybar --default label.padding_left=$PADDINGS
sketchybar --default label.padding_right=$PADDINGS
sketchybar --default background.padding_right=$PADDINGS
sketchybar --default background.padding_left=$PADDINGS
sketchybar --default background.height=26
sketchybar --default background.corner_radius=9
sketchybar --default popup.background.border_width=2
sketchybar --default popup.background.corner_radius=11
sketchybar --default popup.background.border_color=$POPUP_BORDER_COLOR
sketchybar --default popup.background.color=$POPUP_BACKGROUND_COLOR
sketchybar --default popup.background.shadow.drawing=on

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/window_title.sh"

# Center

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
