require("kyle.plugins.impatient")
require("kyle.utils.diable-builtins")
require("kyle.plugins-setup")
require("kyle.core.options")
require("kyle.core.keymaps")
require("kyle.core.colorscheme")
require("kyle.core.autocommands")
