theme = 'catppuccin_macchiato'

[editor]
auto-completion = true
auto-format = true
scrolloff = 8
mouse = false
middle-click-paste = false
line-number = "relative"
cursorline = true
true-color = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false
parents = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[keys.normal]

[keys.normal.space]
"q" = ":q"
"w" = ":w"
